settings:
  default:
    binary_threshold: 90.0
    contrast_adjustment: true
    contrast_max: 95.0
    contrast_min: 5.0
    gausianFilter: true
    gaussian_sigma: 1.0
    inference_input: 96
    inference_instance_segmentation: true
    inference_instance_segmentation_option: Voronoi-Otsu
    inference_instance_segmentation_outline_signma: 2.0
    inference_instance_segmentation_small_object_removal: 25.0
    inference_instance_segmentation_spot_signma: 2.5
    inference_overlap: 50
    inference_perform_threhold: true
    inference_perform_threhold_value: 60
    inference_use_window_choice: true
    inference_window_size: 64
  hanna:
    contrast_adjustment: true
    contrast_min: 5.0
    gausianFilter: true
    gaussian_sigma: 1.0
