settings:
  gausianFilter: True
  gaussian_sigma: 1.0
  contrast_adjustment: True
  contrast_min: 5.0
  contrast_max: 95.0
  binary_threshold: 90.0
  inference_input: 96
  inference_use_window_choice: True
  inference_window_size: 64
  inference_overlap: 50
  inference_perform_threhold: True
  inference_perform_threhold_value: 60
  inference_instance_segmentation: True
  inference_instance_segmentation_option: Voronoi-Otsu
  inference_instance_segmentation_spot_signma: 2.5
  inference_instance_segmentation_outline_signma: 2.0
  inference_instance_segmentation_small_object_removal: 25.0
  